name 'sysadmin-profile'
version '0.0.1'
source ''
author 'Akis Foulidis'
license ''
summary 'Sysadmin-team Profile Module'
description 'Profile aggregator module to define Sysadmin team specific profiles'
project_page ''

#dependency 'foo/bar', '>= 0.0.0'
